defaults:
  - _self_

n_steps: 1.e+6
algo:  # taken from https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml#L74
  learning_rate: 7.3e-4
  buffer_size: 300000
  batch_size: 256
  ent_coef: auto
  gamma: 0.98
  tau: 0.02
  train_freq: 8
  gradient_steps: 8
  learning_starts: 10000
  use_sde: True
  policy_kwargs:
    log_std_init: -3
    net_arch: [400, 300]
