defaults:
  - ppo@algo
  - _self_

parallel: False
batch_T: 128
batch_B: 16
reward_clip_min: -5
reward_clip_max: 5
max_steps_decorrelate: 50
env:
  max_episode_steps: 1000
device: null
model:
  hidden_sizes: [1024, 512, 256]
runner:
  n_steps: 102400  # 50 iterations
  log_interval_steps: 10240  # log every 5 iterations
