defaults:
  - sac_sb3
  - logdirs
  - _self_

hydra:
  job:
    name: walker2d-sac

# hyperparameters for Walker2d are here:
# https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/sac.yml#L104
env_name: Walker2d-v4
log_interval_episodes: 100  # each episode is up to 1000 steps
algo:
  learning_rate: lin_7.3e-4
