defaults:
  - ppo@algo
  - continuous_cartpole@env
  - _self_

hydra:
  job:
    name: continuous-cartpole-ppo
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

parallel: True
batch_T: 128
batch_B: 16
reward_clip_min: -5
reward_clip_max: 5
obs_norm_initial_count: 10000
max_steps_decorrelate: 50
device: null
model:
  hidden_sizes: [64, 64]
  hidden_nonlinearity: Tanh
  mu_nonlinearity: Tanh
  init_log_std: 0.
runner:
  n_steps: 204800  # 100 iterations
  log_interval_steps: 20480  # log every 10 iterations
